export type AchievementOp = ">=" | ">" | "==" | "<=" | "<";

/**
 * Category is a free-form string in the designer. The five `DEFAULT_CATEGORIES`
 * below are always offered in the dropdown; the user can add any other string
 * via the `+ new category…` option. The runtime `AchievementCategory` in
 * `src/config/achievementConfig.ts` is the agent-curated subset that the game
 * actually displays — that union is updated by the agent when wiring a new
 * achievement whose category isn't already known.
 */
export type AchievementCategory = string;

export const DEFAULT_CATEGORIES = [
  "canvas",
  "workshop",
  "ascension",
  "school_office",
  "secret",
] as const;

export interface DesignEffect {
  id: string;  // ephemeral — stripped before saving
  kind: string;
  value: number;
}

export interface DesignCondition {
  stat: string;
  op: AchievementOp;
  value: number;
}

export interface DesignAchievement {
  id: string;
  /**
   * Ephemeral, internal-only identifier. Generated by `addAchievement` (uuid)
   * or by `migrateAchievement` when loading from JSON. Used as the React key
   * and the @dnd-kit `useSortable` id, both of which need a stable value that
   * is NOT the user-editable `id` field (editing `id` would otherwise remount
   * the card on every keystroke). Stripped by `stripEphemeral` in api.ts
   * before saving the JSON.
   */
  _stableKey: string;
  name: string;
  description: string;
  icon: string;
  category: AchievementCategory;
  condition: DesignCondition;
  // Raw text the designer typed for the condition. Source of truth for the
  // input field; parsed best-effort into `condition`. Ephemeral — stripped
  // before saving to the config JSON (like DesignEffect.id).
  conditionText?: string;
  effects: ReadonlyArray<DesignEffect>;
}

export type DesignFile = ReadonlyArray<DesignAchievement>;

export const EMPTY_DESIGN: DesignFile = [];

/**
 * Effect kinds the engine knows how to apply (see `core/multipliers.ts` and
 * `core/schoolMultipliers.ts`). The designer lists these in the kind
 * dropdown; effects whose kind is NOT in this list are flagged "custom" and
 * get a free-text input. Keep in sync with the runtime resolver.
 */
export const KNOWN_EFFECT_KINDS = [
  "paint_mastery_flat",
  "canvas_gold_pct",
  "speed_pct",
  "inspi_pct",
] as const;
