import type { JSX } from "react";
import { useGameStore } from "@/store";
import { formatBig } from "@/core/formatter";
import { Hoverable } from "@/ui/widgets/Hoverable";

/**
 * Currency identifier for the BottomBar widget. Deliberately shadows
 * `CurrencyKey` from currencySlice — that one is store-internal; this one
 * is the UI layer's own naming. Decoupling lets either side rename without
 * forcing the other.
 */
export type CurrencyKind = "gold" | "inspiration" | "fame";

const LABELS: Record<CurrencyKind, string> = {
  gold: "Gold",
  inspiration: "Inspi",
  fame: "Fame",
};

const COLOR_CLASS: Record<CurrencyKind, string> = {
  gold: "text-gold",
  inspiration: "text-inspiration",
  fame: "text-fame",
};

const HOVER_TITLE: Record<CurrencyKind, string> = {
  gold: "Gold",
  inspiration: "Inspiration",
  fame: "Fame",
};

const HOVER_BODY_TEMPLATE: Record<CurrencyKind, (formatted: string) => string> = {
  gold: (v) => `Earned by selling paintings. Current: ${v}.`,
  inspiration: (v) =>
    `Generated by tree parts. Current: ${v}. Reset on ascend.`,
  fame: (v) =>
    `Earned on ascend, spent in skill tree. Current: ${v}. Permanent.`,
};

interface Props {
  kind: CurrencyKind;
}

export function CurrencyDisplay({ kind }: Props): JSX.Element {
  const value = useGameStore((s) => s[kind]);
  return (
    <Hoverable
      title={HOVER_TITLE[kind]}
      body={() => {
        const live = useGameStore.getState()[kind];
        return HOVER_BODY_TEMPLATE[kind](formatBig(live));
      }}
    >
      <span className={"flex items-baseline gap-1 text-sm " + COLOR_CLASS[kind]}>
        <span className="font-semibold">{LABELS[kind]}:</span>
        <span data-testid={`currency-${kind}`}>{formatBig(value)}</span>
      </span>
    </Hoverable>
  );
}
